//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims_Hospital_Zdravo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims_Hospital_Zdravo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality Treatments.
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced Doctors.
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Technologies.
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Customer Satisfaction.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency help.
        /// </summary>
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open hours : 00:00-24:00.
        /// </summary>
        public static string About7 {
            get {
                return ResourceManager.GetString("About7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Secretary.
        /// </summary>
        public static string AboutSecretary {
            get {
                return ResourceManager.GetString("AboutSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens.
        /// </summary>
        public static string Allergens {
            get {
                return ResourceManager.GetString("Allergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment end at :.
        /// </summary>
        public static string AppEndAt {
            get {
                return ResourceManager.GetString("AppEndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment start at :.
        /// </summary>
        public static string AppStartAt {
            get {
                return ResourceManager.GetString("AppStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already available&amp;#xD;&amp;#xA;supplies :.
        /// </summary>
        public static string AvailableSupplies {
            get {
                return ResourceManager.GetString("AvailableSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose doctor speciality :.
        /// </summary>
        public static string ChooseDoctor {
            get {
                return ResourceManager.GetString("ChooseDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose room :.
        /// </summary>
        public static string ChooseRoom {
            get {
                return ResourceManager.GetString("ChooseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-mm-dd.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If patient doesn&apos;t exist,&amp;#xD;&amp;#xA;please create medical  record first!.
        /// </summary>
        public static string DoesPatientExist {
            get {
                return ResourceManager.GetString("DoesPatientExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency examination.
        /// </summary>
        public static string EmergencyExamination {
            get {
                return ResourceManager.GetString("EmergencyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End at :.
        /// </summary>
        public static string EndAt {
            get {
                return ResourceManager.GetString("EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name :.
        /// </summary>
        public static string EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation :.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Zdravo.
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string LblAppointments {
            get {
                return ResourceManager.GetString("LblAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string LblContact {
            get {
                return ResourceManager.GetString("LblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string LblEquipment {
            get {
                return ResourceManager.GetString("LblEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free days requests.
        /// </summary>
        public static string LblFreeDays {
            get {
                return ResourceManager.GetString("LblFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LblHome {
            get {
                return ResourceManager.GetString("LblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical records.
        /// </summary>
        public static string LblMedicalRecords {
            get {
                return ResourceManager.GetString("LblMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        public static string LblMeetings {
            get {
                return ResourceManager.GetString("LblMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LblProfile {
            get {
                return ResourceManager.GetString("LblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string LblSignOut {
            get {
                return ResourceManager.GetString("LblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string Marital_status {
            get {
                return ResourceManager.GetString("Marital status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedicalAllergens.
        /// </summary>
        public static string MedicalAllergens {
            get {
                return ResourceManager.GetString("MedicalAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting start at :.
        /// </summary>
        public static string MeetingAt {
            get {
                return ResourceManager.GetString("MeetingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non registerd patients:.
        /// </summary>
        public static string NonRegistered {
            get {
                return ResourceManager.GetString("NonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional attendees :.
        /// </summary>
        public static string OptionalAttendees {
            get {
                return ResourceManager.GetString("OptionalAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other allergens:.
        /// </summary>
        public static string OtherAllergens {
            get {
                return ResourceManager.GetString("OtherAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others :.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient allergic to:.
        /// </summary>
        public static string PatientAllergicTo {
            get {
                return ResourceManager.GetString("PatientAllergicTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient medical&amp;#xD;&amp;#xA;allergens:.
        /// </summary>
        public static string PatientMedicalAllergens {
            get {
                return ResourceManager.GetString("PatientMedicalAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNum {
            get {
                return ResourceManager.GetString("PhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity :.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason :.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status :.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attendees :.
        /// </summary>
        public static string RequiredAttendees {
            get {
                return ResourceManager.GetString("RequiredAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule meeting.
        /// </summary>
        public static string ScheduleMeeting {
            get {
                return ResourceManager.GetString("ScheduleMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary.
        /// </summary>
        public static string Secretary {
            get {
                return ResourceManager.GetString("Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary Ana Jovanovic is an experienced&amp;#xD;&amp;#xA;secretary who is constantly working on&amp;#xD;&amp;#xA;improving her skills..
        /// </summary>
        public static string SecretaryInfo {
            get {
                return ResourceManager.GetString("SecretaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select appointment type :.
        /// </summary>
        public static string SelectAppType {
            get {
                return ResourceManager.GetString("SelectAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select patient:.
        /// </summary>
        public static string SelectPatient {
            get {
                return ResourceManager.GetString("SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select room :.
        /// </summary>
        public static string SelectRoom {
            get {
                return ResourceManager.GetString("SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at:.
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme :.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing appointments.
        /// </summary>
        public static string ttAppointments {
            get {
                return ResourceManager.GetString("ttAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ttCreate {
            get {
                return ResourceManager.GetString("ttCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment acquisition.
        /// </summary>
        public static string ttEquipment {
            get {
                return ResourceManager.GetString("ttEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing free days.
        /// </summary>
        public static string ttFreeDays {
            get {
                return ResourceManager.GetString("ttFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ttNext {
            get {
                return ResourceManager.GetString("ttNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
