//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims_Hospital_Zdravo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_sr_LATN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_sr_LATN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims_Hospital_Zdravo.Properties.Resources.sr-LATN", typeof(Resources_sr_LATN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma kvalitetni tretmani.
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskusni doktori.
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najnovije tehnologije.
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma zadovoljni pacijenti.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brza pomoć.
        /// </summary>
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multinacionalni.
        /// </summary>
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radno vreme : 00:00-24:00.
        /// </summary>
        public static string About7 {
            get {
                return ResourceManager.GetString("About7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled se završava u :.
        /// </summary>
        public static string AppEndAt {
            get {
                return ResourceManager.GetString("AppEndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled počinje u :.
        /// </summary>
        public static string AppStartAt {
            get {
                return ResourceManager.GetString("AppStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi specijalnost lekara :.
        /// </summary>
        public static string ChooseDoctor {
            get {
                return ResourceManager.GetString("ChooseDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako pacijent ne postoji, molim Vas prvo kreirajte medicinski karton!.
        /// </summary>
        public static string DoesPatientExist {
            get {
                return ResourceManager.GetString("DoesPatientExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završava se u :.
        /// </summary>
        public static string EndAt {
            get {
                return ResourceManager.GetString("EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnica Zdravo.
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik :.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string LblAppointments {
            get {
                return ResourceManager.GetString("LblAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string LblContact {
            get {
                return ResourceManager.GetString("LblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema.
        /// </summary>
        public static string LblEquipment {
            get {
                return ResourceManager.GetString("LblEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slobodni dani.
        /// </summary>
        public static string LblFreeDays {
            get {
                return ResourceManager.GetString("LblFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        public static string LblHome {
            get {
                return ResourceManager.GetString("LblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinski kartoni.
        /// </summary>
        public static string LblMedicalRecords {
            get {
                return ResourceManager.GetString("LblMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastanci.
        /// </summary>
        public static string LblMeetings {
            get {
                return ResourceManager.GetString("LblMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string LblProfile {
            get {
                return ResourceManager.GetString("LblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string LblSignOut {
            get {
                return ResourceManager.GetString("LblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za neregistrovane pacijente:.
        /// </summary>
        public static string NonRegistered {
            get {
                return ResourceManager.GetString("NonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite tip pregleda :.
        /// </summary>
        public static string SelectAppType {
            get {
                return ResourceManager.GetString("SelectAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite pacijenta:.
        /// </summary>
        public static string SelectPatient {
            get {
                return ResourceManager.GetString("SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite sobu :.
        /// </summary>
        public static string SelectRoom {
            get {
                return ResourceManager.GetString("SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počinje u :.
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema :.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljaj pregledima.
        /// </summary>
        public static string ttAppointments {
            get {
                return ResourceManager.GetString("ttAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj.
        /// </summary>
        public static string ttCreate {
            get {
                return ResourceManager.GetString("ttCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabavi opremu.
        /// </summary>
        public static string ttEquipment {
            get {
                return ResourceManager.GetString("ttEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljaj slobodnim danima.
        /// </summary>
        public static string ttFreeDays {
            get {
                return ResourceManager.GetString("ttFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        public static string ttNext {
            get {
                return ResourceManager.GetString("ttNext", resourceCulture);
            }
        }
    }
}
